services:
  n8n:
    image: n8nio/n8n:1.121.3
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change-me
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/files
    restart: unless-stopped

  n9n:
    image: n8nio/n8n:latest
    container_name: n9n
    profiles: ["n9n"]
    ports:
      - "5679:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=change-me
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./n9n_data:/home/node/.n8n
      - ./n9n_files:/files
    restart: unless-stopped
